### ISSUE TITLE
Running grpo with lora, the model response is "!!!!!!"

### ISSUE THREAD

**Issue by mootutu** [verl-project/verl#3159]
I trained Qwen2.5-3B-Instruct with GRPO using two almost identical scripts: one without LoRA and one with LoRA. The only difference between them is the LoRA configuration. However, when using LoRA, the model’s output always degenerates into "!!!!!!!!!!!!".
<details>
<summary>grpo setting and output</summary>

**scripts**
```sh
set -x
# GPU
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
GPU_MEMORY_UTILIZATION=0.6
N_GPUS_PER_NODE=8
NNODES=1
TENSOR_PARALLEL_SIZE=2
# model
MODEL="Qwen2.5/Qwen2.5-3B-Instruct"
ALL_MODEL="/mnt/d/All/models"
MODEL_PATH=$ALL_MODEL/$MODEL
# dataset
DATASET="gsm8k"
ALL_DATA="/mnt/d/verl4test/data"
DATA_PATH=$ALL_DATA/$DATASET
# rollout
ROLLOUT_N=5
# training
GAE="grpo"
LORA_RANK=32
LORA_ALPHA=32
LR=3e-6
EPOCH=15
BATCH_SIZE=8
PROMPT_LENGTH=512
RESPONSE_LENGTH=1024
MINI_BATCH_SIZE=8
MICRO_BATCH_SIZE=1
# logger
DATE=$(date +%Y%m%d)
TIME_TAG=$(date +%H%M%S)
SWANLAB_KEY=
# EXPERIMENT_NAME="lora_test_${MODEL}_${DATASET}"
PROJECT_NAME="lora_test"
LOG_NAME="${GAE}_${MODEL}_${DATASET}_${DATE}_${TIME_TAG}"
OUTPUT_DIR="/mnt/d/verl4test/checkpoints/${PROJECT_NAME}/${LOG_NAME}"

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=$GAE \
    data.train_files=$DATA_PATH/train.parquet \
    data.val_files=$DATA_PATH/test.parquet \
    data.train_batch_size=$BATCH_SIZE \
    data.max_prompt_length=$PROMPT_LENGTH \
    data.max_response_length=$RESPONSE_LENGTH \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.shuffle=False \
    actor_rollout_ref.model.path=$MODEL_PATH \
    actor_rollout_ref.model.use_shm=True \
    actor_rollout_ref.model.lora_rank=$LORA_RANK \
    actor_rollout_ref.model.lora_alpha=$LORA_ALPHA \
    actor_rollout_ref.actor.optim.lr=$LR \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=$MINI_BATCH_SIZE \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=$MICRO_BATCH_SIZE \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=$MICRO_BATCH_SIZE \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$TENSOR_PARALLEL_SIZE \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=$GPU_MEMORY_UTILIZATION \
    actor_rollout_ref.rollout.n=$ROLLOUT_N \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.rollout.layered_summon=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=$MICRO_BATCH_SIZE \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console","swanlab"]' \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$LOG_NAME \
    trainer.n_gpus_per_node=$N_GPUS_PER_NODE \
    trainer.nnodes=$NNODES \
    trainer.save_freq=20 \
    trainer.test_freq=5 \
    trainer.default_local_dir=$OUTPUT_DIR \
    trainer.total_epochs=$EPOCH $@
```

**output(grpo)**
<img width="3450" height="1528" alt="Image" src="https://github.com/user-attachments/assets/9dc1afb1-0863-464b-82df-d260ba9c2700" />
</details>

<details>
<summary>grpo_lora setting and output</summary>

```sh

set -x
# GPU
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
GPU_MEMORY_UTILIZATION=0.6
N_GPUS_PER_NODE=8
NNODES=1
TENSOR_PARALLEL_SIZE=2
# model
MODEL="Qwen2.5/Qwen2.5-3B-Instruct"
ALL_MODEL="/mnt/d/All/models"
MODEL_PATH=$ALL_MODEL/$MODEL
# dataset
DATASET="gsm8k"
ALL_DATA="/mnt/d/verl4test/data"
DATA_PATH=$ALL_DATA/$DATASET
# rollout
ROLLOUT_N=5
# training
GAE="grpo"
LORA_RANK=32
LORA_ALPHA=32
LR=3e-6
EPOCH=15
BATCH_SIZE=8
PROMPT_LENGTH=512
RESPONSE_LENGTH=1024
MINI_BATCH_SIZE=8
MICRO_BATCH_SIZE=1
# logger
DATE=$(date +%Y%m%d)
TIME_TAG=$(date +%H%M%S)
SWANLAB_KEY=
# EXPERIMENT_NAME="lora_test_${MODEL}_${DATASET}"
PROJECT_NAME="lora_test"
LOG_NAME="${GAE}_${MODEL}_${DATASET}_${DATE}_${TIME_TAG}"
OUTPUT_DIR="/mnt/d/verl4test/checkpoints/${PROJECT_NAME}/${LOG_NAME}"

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=$GAE \
    data.train_files=$DATA_PATH/train.parquet \
    data.val_files=$DATA_PATH/test.parquet \
    data.train_batch_size=$BATCH_SIZE \
    data.max_prompt_length=$PROMPT_LENGTH \
    data.max_response_length=$RESPONSE_LENGTH \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.shuffle=False \
    actor_rollout_ref.model.path=$MODEL_PATH \
    actor_rollout_ref.model.use_shm=True \
    actor_rollout_ref.actor.optim.lr=$LR \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=$MINI_BATCH_SIZE \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=$MICRO_BATCH_SIZE \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=$MICRO_BATCH_SIZE \
    actor_rollout_ref.rollout.tensor_model_parallel_size=$TENSOR_PARALLEL_SIZE \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=$GPU_MEMORY_UTILIZATION \
    actor_rollout_ref.rollout.n=$ROLLOUT_N \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.rollout.layered_summon=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=$MICRO_BATCH_SIZE \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console","swanlab"]' \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$LOG_NAME \
    trainer.n_gpus_per_node=$N_GPUS_PER_NODE \
    trainer.nnodes=$NNODES \
    trainer.save_freq=20 \
    trainer.test_freq=5 \
    trainer.default_local_dir=$OUTPUT_DIR \
    trainer.total_epochs=$EPOCH $@

```

<img width="3402" height="1448" alt="Image" src="https://github.com/user-attachments/assets/3b9a6a3b-6435-4a2b-991e-8d3ad34d336d" />
</details>

**Comment by Yuyang-0** [comment]
same on a100 with Qwen2.5-32B-Instruct

**Comment by mootutu** [comment]
> same on a100 with Qwen2.5-32B-Instruct

Did you manage to solve it now? I debugged it a few times but didn’t seem to find the problem 🥲.

**Comment by Yuyang-0** [comment]
I think the problem lies in the vllm generation rather than the training process or the model itself. I tried to train the 4B model use the exactly same script of 32B model, and observed the same problem. 

I tried to unset the data.val_batch_size with or without setting the vllm batch size, and the problem was gone. That means the validation does not run in a loop but sent to the vllm generator in one run. I still don't know why is this, and don't know if this can fix the problem entirely. Maybe someone can investigate more.

**Comment by mootutu** [comment]
> I think the problem lies in the vllm generation rather than the training process or the model itself. I tried to train the 4B model use the exactly same script of 32B model, and observed the same problem.
> 
> I tried to unset the data.val_batch_size with or without setting the vllm batch size, and the problem was gone. That means the validation does not run in a loop but sent to the vllm generator in one run. I still don't know why is this, and don't know if this can fix the problem entirely. Maybe someone can investigate more.

It appears that my data.val_batch_size is null; however, I still encounter

**Comment by Yuyang-0** [comment]
Can you try this script?

```
# -*- coding: utf-8 -*-
# export CUDA_VISIBLE_DEVICES=4,5,6,7
NOW=$(date +%Y%m%d)
export WANDB_DIR=gsm8k-grpo-lora-qwen2.5-32b-${NOW}
export WANDB_PROJECT=${WANDB_DIR}
export WANDB_EXP=32b-${NOW}
# MODEL_PATH=/data1/model/Qwen3-30B-A3B-Instruct-2507
MODEL_PATH=/data/model/Qwen/Qwen3-4B-Instruct-2507

set -x

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=${HOME}/data/gsm8k/train.parquet \
    data.val_files=${HOME}/data/gsm8k/test.parquet \
    data.train_batch_size=1024 \
    data.max_prompt_length=512 \
    data.max_response_length=1024 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.shuffle=False \
    actor_rollout_ref.model.path=$MODEL_PATH  \
    actor_rollout_ref.model.use_shm=True  \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.lora_rank=32 \
    actor_rollout_ref.model.lora_alpha=32 \
    actor_rollout_ref.model.target_modules=all-linear \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.rollout.max_num_seqs=512 \
    actor_rollout_ref.rollout.max_model_len=1536 \
    actor_rollout_ref.rollout.max_num_batched_tokens=1536 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name=${WANDB_PROJECT} \
    trainer.experiment_name=${WANDB_EXP} \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=5 \
    trainer.total_epochs=1 $@ 2>&1 | tee ${WANDB_PROJECT}.log
```

**Comment by mootutu** [comment]
It still doesn't work :(

**Comment by kfallah** [comment]
Hi, I am also having this issue with Qwen 2.5 VL 3b using a LoRA. I tried a git bisect, and was able to trace it to the following PR: 
https://github.com/volcengine/verl/pull/3019

[I believe this is the problematic line](https://github.com/volcengine/verl/pull/3019/files#diff-e12e758b29fcac6e5831bae88c8dbba4be0fc1847c762aba38642a024d63d4a1R207.). After setting to `sleep=1`, it works again.

**Comment by mootutu** [comment]
> Hi, I am also having this issue with Qwen 2.5 VL 3b using a LoRA. I tried a git bisect, and was able to trace it to the following PR: [#3019](https://github.com/volcengine/verl/pull/3019)
> 
> [I believe this is the problematic line](https://github.com/volcengine/verl/pull/3019/files#diff-e12e758b29fcac6e5831bae88c8dbba4be0fc1847c762aba38642a024d63d4a1R207.). After setting to `sleep=1`, it works again.

Thanks for sharing this! 🙌 Your method was super helpful — I went ahead and set all the sleep values in the linked lines to 1, and now the model trains just fine. 😄

This issue would’ve been so hard to track down without git bisect — really appreciate you tracing it out! 🕵️‍♂️✨

**Comment by kfallah** [comment]
Unfortunately, I believe there may be another issue. Throughout training, I am getting the exact same validation rollouts for a given prompt. This leads me to think the LoRA may not be loading as expected. I will try and debug and see if I can find anything.

Edit: this extra issue only occurs if (1) using VLM, (2) using LoRA, (3) using layered summon. Put up a fix here: https://github.com/volcengine/verl/pull/3231

**Comment by techkang** [comment]
@kfallah @QwQwangg Can you share your vllm version? vllm sleep level=2 bug has been fixed since version 0.8.5 https://github.com/volcengine/verl/blob/4c7812c40b473867b4ba1d6d5e8687841578aa66/verl/third_party/vllm/__init__.py#L48-L49.

**Comment by YubaoZhao** [comment]
> [@kfallah](https://github.com/kfallah) [@QwQwangg](https://github.com/QwQwangg) Can you share your vllm version? vllm sleep level=2 bug has been fixed since version 0.8.5
> 
> [verl/verl/third_party/vllm/__init__.py](https://github.com/volcengine/verl/blob/4c7812c40b473867b4ba1d6d5e8687841578aa66/verl/third_party/vllm/__init__.py#L48-L49)
> 
> Lines 48 to 49 in [4c7812c](/volcengine/verl/commit/4c7812c40b473867b4ba1d6d5e8687841578aa66)
> 
>  if vs.parse(package_version) >= vs.parse("0.8.5"): 
>      VLLM_SLEEP_LEVEL = 2 
> .

I installed vLLM version 0.8.5.post1, and when I trained GRPO with LoRA, I still encountered this issue. After modifying `VLLM_SLEEP_LEVEL = 1`, it worked and the response was normal.

**Comment by kfallah** [comment]
I encounter this issue with vLLM 0.10.0

**Comment by mootutu** [comment]
I encounter this issue with VLLM v0.8.5

**Comment by xvrong** [comment]
I encounter this issue with VLLM v0.11.0

**Comment by iFe1er** [comment]
I encounter this issue with VLLM v0.12.0
